name: Assess Policy as Code

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: contrast-security-oss/example-teamserver-api-scripts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/contrast-security-oss/assess-policy-as-code:main
          options: -v ${{ github.workspace }}/output:/usr/src/app/output -e CONTRAST__API__URL=https://apptwo.contrastsecurity.com -e CONTRAST__API__API_KEY=${{ secrets.CONTRAST_API_KEY }} -e CONTRAST__API__AUTH_HEADER=${{ secrets.CONTRAST_AUTH_HEADER }}
          run: python /usr/src/app/contrast_policy_as_code.py -o ${{ secrets.CONTRAST_ORGANIZATION_ID }}

      - uses: numtide/clean-git-action@v1
